### ISSUE TITLE
Meta: version 2.0.0

### ISSUE THREAD

**Issue by Errorname** [Errorname/prisma-multi-tenant#10]
This issue will reference all the work that needs to be done for the release of the 2.0.0 version:

**Documentation:**
- [x] Contributing guide
- [x] Example: Basic JS
- [x] Example: Basic TS
- [ ] Example: Nexus
- [ ] Better explains that PMT is a wrapper of Prisma

**Quality:**
- [x] Tests (CLI)
- [x] Tests (Library)
- [x] Reduce overall size of the library (From 134 kB at alpha7 to 78.8 kB at alpha9)

**Features:**
- [x] `prisma-multi-tenant migrate save`
- [x] Provide Management interface in lib
- [x] `prisma-multi-tenant new management`
- [x] Improve Error-handling
- [x] Rework env handling (See prisma/prisma-client-js#454)
- [x] `prisma-multi-tenant eject`

**Bug fixes:**
- [x] Fix subsequent migrate crash on datasource renaming (See prisma/lift#265)
- [x] Fix #12 
- [x] Fix #14 
- [x] Use preview20
- [x] Fix issues on windows

**Nice to have:**
- [x] Use default env in Prisma Schema (See #6)
- [ ] Export/Import data from/to a tenant (See #7)
- [ ] Allow tenants from multiple providers (See #8)
- [ ] Use `--delete-db` on `pmt delete` (See prisma/migrate#350)
- [x] Allow `--name foo` syntax
- [x] Read `.env` file if it exists
- [x] Add `--env` option

**Comment by Errorname** [comment]
Prisma-multi-tenant@2.0.0 is out 🥳
